// <auto-generated />
using System;
using DavinciEPA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DavinciEPA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DavinciEpaDbContext))]
    partial class DavinciEpaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DavinciEPA.Core.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResourceReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogEntries", (string)null);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.CoverageRequirementEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsMet")
                        .HasColumnType("bit");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PriorAuthorizationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequirementCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequirementDescription")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrderReference");

                    b.HasIndex("PriorAuthorizationRequestId");

                    b.ToTable("CoverageRequirementEvaluations", (string)null);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.DocumentationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PriorAuthorizationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionnaireCanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("QuestionnaireResponseReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PriorAuthorizationRequestId");

                    b.ToTable("DocumentationRequirements", (string)null);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.PriorAuthorizationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Disposition")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DispositionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PatientIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PatientIdentifier");

                    b.HasIndex("Status");

                    b.ToTable("PriorAuthorizationRequests", (string)null);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.RuleEvaluationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("PriorAuthorizationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PriorAuthorizationRequestId");

                    b.ToTable("RuleEvaluationLogs", (string)null);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.CoverageRequirementEvaluation", b =>
                {
                    b.HasOne("DavinciEPA.Core.Entities.PriorAuthorizationRequest", null)
                        .WithMany("CoverageRequirements")
                        .HasForeignKey("PriorAuthorizationRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.DocumentationRequirement", b =>
                {
                    b.HasOne("DavinciEPA.Core.Entities.PriorAuthorizationRequest", null)
                        .WithMany("DocumentationRequirements")
                        .HasForeignKey("PriorAuthorizationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DavinciEPA.Core.Entities.PriorAuthorizationRequest", b =>
                {
                    b.Navigation("CoverageRequirements");

                    b.Navigation("DocumentationRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
